### ISSUE TITLE
Ender lock dupe

### ISSUE THREAD

**Issue by CorGaming** [gigaherz/Enderthing#3] opened 2016-04-29 23:08 UTC
After you ender lock a vanilla chest, if u build another one and shift-right click that same chest it pops Ender lock for days xD. Every shift right-click pops 1. At first I thought it was creative bug, but tested in survival and happens too. This way you can dupe Ender Locks for days :).

**Comment by gigaherz** [comment] 2016-04-29 23:15
Hmm... it should "use" the one in the hand, if it doesn't, then THAT is the bug. The idea is that it returns whatever was already in it, so that you don't lose the previous combination, but the stack size of the lock should be reduced by 1...

**Comment by gigaherz** [comment] 2016-04-29 23:31
After investigating further, I can't reproduce your issue: while in survival mode, the stack size gets reduced correctly in both the 1.8.9 and 1.9 versions (v0.5.2). 

However, I did notice a bug: If you apply a GLOBAL lock on a PRIVATE chest, the colors get applied without changing the chest to global, and the returned lock is private, so you can use it to convert global locks into private locks without spending nuggets. Oops.

**Comment by CorGaming** [comment] 2016-04-29 23:36
well, I will try again when I do a full reset of the world and see if was some problem with configuring mods and changing from creative to survival while doing so. Thx for the fast answer and for finding a bug xD, and yes forgot to mention but it was in v0.5.1, but I download last version too before trying again.

**Comment by CorGaming** [comment] 2016-04-29 23:41
Well, I made a fast try just to help you faster and you are correct...no dupe...probably it was related to creative/survival changes. Tried every thing in survival and no dupe at all. Thx anyway for your time in doing this mod. I was missing this to help with the farms :P

**Comment by gigaherz** [comment] 2016-04-29 23:41
The only change between 0.5.1 and 0.5.2 is a recipe crash fix, so it should be the same.

**Comment by CorGaming** [comment] 2016-04-29 23:44
Yup all fine. Was a dupe in creative because u dont loose stack and instead it creates more and more, but I did a clean login in survival and crafted every thing in survival and no dupe at all :).

**Comment by gigaherz** [comment] 2016-04-29 23:45
I'll be closing this, then. :)

**Comment by gigaherz** [comment] 2016-04-29 23:45
BTW, expect a 0.5.3 soon.

**Closed as completed by gigaherz** 2016-04-29 23:45 UTC
