### ISSUE TITLE
items go to nirvana if u change the color code during item transfer

### ISSUE THREAD

**Issue by Sailren** [gigaherz/Enderthing#1] opened 2016-04-27 10:46 UTC
this is what i have tested, the "building" im in is from roguelike dungeons

http://abload.de/img/2016-04-27_12.42.42_2xksdv.png

http://abload.de/img/2016-04-27_12.42.44tcszx.png

http://abload.de/img/2016-04-27_12.42.48kkscf.png

http://abload.de/img/2016-04-27_12.42.29o4sdq.png

need to test if this only happens in creative mode

**Comment by gigaherz** [comment] 2016-04-27 11:01
Hmmm I'll have to debug this situation, but I don't see how this would lose items :/

Meanwhile, can you check on a white-white-white chest? If somehow an operation "loses" the id, it would use 0, which corresponds to white-white-white.

EDIT: By "check on a white-white-white" I meant check if the items landed into one with that code,

**Comment by Sailren** [comment] 2016-04-27 11:03
atleast u can see my setup here, perhaps it uses ghost items, because one of the chests still transfers stuff

yeah, if u change the color and look in chest there is nothing, but when u shut down the instance and open it again, they are there

**Comment by gigaherz** [comment] 2016-04-27 11:09
I set up an equivalent configuration of chests, and I dumped a bunch of things into it, and it never lost anything. Are you on a server? I'll try if a server makes a difference, next.

**Comment by gigaherz** [comment] 2016-04-27 11:24
I managed to run both the server and client on this laptop (painfully slowly), and although the client data sometimes doesn't quite update fast enough to show the item passing through, it does appear to still work correctly without losing items.

However, i am in a debug environment, with deobfuscated names and such. I'll try a reobfuscated build on a normal MC installation, but so far it looks like I can't reproduce the issue.

**Comment by Sailren** [comment] 2016-04-27 11:32
that could be the thing, this update of items in chest

**Comment by gigaherz** [comment] 2016-04-27 11:56
I'll close this for now. If you can confirm that you lost items, I'll reopen.

**Closed as completed by gigaherz** 2016-04-27 11:56 UTC
