### ISSUE TITLE
Ender Chests not inter dimensionally

### ISSUE THREAD

**Issue by MrJoki007** [gigaherz/Enderthing#8] opened 2016-05-19 19:35 UTC
I wanted to use this enderchest for my query in my mining dimension but it seems that theres a bug?, that the enderchest is an own in every dimension

**Comment by gigaherz** [comment] 2016-05-19 19:50
It shouldn't be...

I'm most definitely using the global storage ssytem `world.getMapStorage()` vs `world.getPerWorldStorage()`, so if it's not shared, either you made a mistake, or there's a forge bug (EDIT: No scratch that, WorldSavedData is from Mojang, that wouldn't make sense).

In fact, I just tested it, and I can't reproduce the issue. Are you SURE you are using the same chest? One of them may be public and the other private? Or maybe they are bound to different players?

**Comment by MrJoki007** [comment] 2016-05-19 20:08
Yeah i cheated them

**Comment by MrJoki007** [comment] 2016-05-19 20:08
I use the version 1.8.9-0.6.5 on the forge version 1902

**Comment by gigaherz** [comment] 2016-05-19 20:21
Well I rechecked on 1.8.9 to make sure, and all I can say is, v0.6.6 works just fine. I'm checking on a non-dev forge installation.

Meanwhile, for the sake of removing variables, are you using it along with any mods? if so, can you gist/pastebin a list? and test the mod on your end without any other mods?

**Comment by MrJoki007** [comment] 2016-05-19 20:22
He says in singleplayer it works but on server it doesnt

**Comment by gigaherz** [comment] 2016-05-19 20:24
Hmm so it's an issue only on a server? I'll try that next.

**Comment by gigaherz** [comment] 2016-05-19 20:29
Nope still can't reproduce.

**Comment by MrJoki007** [comment] 2016-05-19 20:36
OMG i know whats breaking it

**Comment by gigaherz** [comment] 2016-05-19 20:43
Hmm?

**Comment by MrJoki007** [comment] 2016-05-19 20:44
Im using sponge on my forge server and i just removed sponge and it worked again

**Comment by gigaherz** [comment] 2016-05-19 20:46
Ohh, so sponge messes up the WorldSavedData somehow? That sounds annoying. You may want to create an issue on sponge's tracker, and link to this issue for reference. I'm closing this unless/until more information reveals I'm doing something wrong. ;P

**Comment by MrJoki007** [comment] 2016-05-19 20:46
Could you look short over my sponge config? Maybe theres something you have to set that it works ^^

**Closed as completed by gigaherz** 2016-05-19 20:46 UTC

**Comment by gigaherz** [comment] 2016-05-19 20:54
I just added forge to the test server I set up earlier, and I can confirm that it IS an issue with Sponge. It would be best if you report the issue there. I'm happy to cooperate with them in any way I can, but I don't really have the time to debug their changes to see why they don't allow my data to be accessed from other dimensions.

**Comment by MrJoki007** [comment] 2016-05-19 21:01
Yeah i made a bug report in the sponge forum

**Comment by gigaherz** [comment] 2016-05-19 21:02
Can you link to it, for reference?

**Comment by MrJoki007** [comment] 2016-05-19 21:03
https://forums.spongepowered.org/t/sponge-problem-with-enderthing-enderchests/12836

**Comment by gigaherz** [comment] 2016-05-19 21:06
I'm talking with the sponge devs right now.

**Comment by Zidane** [comment] 2016-05-19 21:10
@MrJoki007 @gigaherz 

I'm fairly aware of the issue, I'll push a fix this evening. Apologies for that!

**Comment by MrJoki007** [comment] 2016-05-19 21:11
Can i know what is evening for you? Would be cool because i live in germany and dont know what your timezone is ^^

**Comment by MrJoki007** [comment] 2016-05-19 21:15
Thanks for fixing it so fast ^^

**Comment by Zidane** [comment] 2016-05-19 21:20
Oh, I'm Central Standard Time so 4:20PM currently. I'll be home by 6PM so sometime after that.

**Comment by MrJoki007** [comment] 2016-05-19 21:22
Ok for me its 11:20PM :D

**Comment by Zidane** [comment] 2016-05-20 03:46
@MrJoki007 @gigaherz 

I've pushed a change to SpongeCommon (the master codebase) and have propogated this to SpongeForge (which is SpongeAPI on top of Forge). It'll be available for download shortly.

Thanks for the feedback! Let me know if this solves your issue.

EDIT: https://github.com/SpongePowered/SpongeCommon/commit/878bb52b797a28a7e2e5699610e864372be5a09a

There is the commit if curious (there is two additional ones afterwards to fix oversights).

**Comment by MrJoki007** [comment] 2016-05-20 12:12
@Zidane  I tried the newest sponge version but now my server crashes with this error http://hastebin.com/ciwamixuza.md

**Comment by MrJoki007** [comment] 2016-05-20 12:20
@Zidane 
I tried the newest version but my server crashes now with this error: http://hastebin.com/demekaquyi.md

**Comment by gigaherz** [comment] 2016-05-20 13:54
@MrJoki007 you should provide the "fml-server-latest.log" file from the server, if possible (gist/pastebin), and you should report that on the spongeforge issue tracker, not here. ;P

https://github.com/SpongePowered/SpongeForge/issues
