### ISSUE TITLE
items get voided 

### ISSUE THREAD

**Issue by shrael** [gigaherz/Enderthing#12] opened 2016-07-08 14:37 UTC
hmm not sure if this is a bug for the mod or not but using ender io item conduits and quantum storage it doesnt go into the storage rather it voids the item, trying this with cobble and dirt, also tried from the top and still a no go. this is for 1.10

**Comment by gigaherz** [comment] 2016-07-08 14:42
Does it work if you put them on a chest? How about if you use a hopper to move them into the quantum storage?

**Comment by shrael** [comment] 2016-07-08 15:13
hey that works its a fix for now also works with conduits attached to hopper, its a little slow though

**Comment by gigaherz** [comment] 2016-07-08 15:16
So the problem is with inserting to the quantum storage, or removing from mine? I'd like to know that.

**Comment by shrael** [comment] 2016-07-08 15:18
no it looks like just inserting.removing is fine

**Comment by gigaherz** [comment] 2016-07-08 15:26
Okay closing this then :)

**Closed as completed by gigaherz** 2016-07-08 15:26 UTC
