### ISSUE TITLE
1.8.9-Enderthing chest w/ Storage Network Mod

### ISSUE THREAD

**Issue by WenXin20** [gigaherz/Enderthing#11] opened 2016-06-24 03:20 UTC
The enderthing chests don't connect with storage network cables.

**Comment by gigaherz** [comment] 2016-06-24 10:15
does the storage network not support the IItemHandler capability? If so, then it's not my problem. If they are supposed to, then I'll take a look.

**Comment by WenXin20** [comment] 2016-06-24 14:27
I don't know, I think it does.

**Comment by gigaherz** [comment] 2016-06-24 15:59
Is this issue specific to 1.8.9? I just tested on the 1.9.4 version, with neotech furnace generator to power the network master block, and it worked just fine.

Also, make sure you are using a public chest, or a private chest with an ID card to bind it to your player.

I'll do a quick test with 1.8.9 to confirm, I suppose.

**Comment by gigaherz** [comment] 2016-06-24 16:02
Oh, I did find an issue -- the import stops working if you change the color code using dyes. Breaking the chest and placing it back should allow it to work again, though.

**Comment by gigaherz** [comment] 2016-06-24 16:10
Okay confirmed: Storage Network id NOT support IItemHandler until 5 days ago, and only on 1.9.4: https://github.com/MrRiegel/Storage-Network/commit/7778868704221e1f92233f7a40841dc482e8a49f

I'm closing this as "not my fault", since I'm not going to implement new features on 1.8.9, let alone IInventory support on my chests.

**Closed as completed by gigaherz** 2016-06-24 16:10 UTC
Labels: wontfix
